//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nCreditReport.CreditSafeSeGetData {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://webservice.creditsafe.se/getdata/", ConfigurationName="CreditSafeSeGetData.GetDataSoap")]
    public interface GetDataSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://webservice.creditsafe.se/getdata/GetDataBySecure", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        nCreditReport.CreditSafeSeGetData.GETDATA_RESPONSE GetDataBySecure(nCreditReport.CreditSafeSeGetData.GETDATA_REQUEST GetData_Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://webservice.creditsafe.se/getdata/GetDataBySecure", ReplyAction="*")]
        System.Threading.Tasks.Task<nCreditReport.CreditSafeSeGetData.GETDATA_RESPONSE> GetDataBySecureAsync(nCreditReport.CreditSafeSeGetData.GETDATA_REQUEST GetData_Request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservice.creditsafe.se/getdata/")]
    public partial class GETDATA_REQUEST : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Account accountField;
        
        private string block_NameField;
        
        private string searchNumberField;
        
        private string formattedOutputField;
        
        private string lODCustFreeTextField;
        
        private string mobileField;
        
        private string emailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Account account {
            get {
                return this.accountField;
            }
            set {
                this.accountField = value;
                this.RaisePropertyChanged("account");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Block_Name {
            get {
                return this.block_NameField;
            }
            set {
                this.block_NameField = value;
                this.RaisePropertyChanged("Block_Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SearchNumber {
            get {
                return this.searchNumberField;
            }
            set {
                this.searchNumberField = value;
                this.RaisePropertyChanged("SearchNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string FormattedOutput {
            get {
                return this.formattedOutputField;
            }
            set {
                this.formattedOutputField = value;
                this.RaisePropertyChanged("FormattedOutput");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string LODCustFreeText {
            get {
                return this.lODCustFreeTextField;
            }
            set {
                this.lODCustFreeTextField = value;
                this.RaisePropertyChanged("LODCustFreeText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Mobile {
            get {
                return this.mobileField;
            }
            set {
                this.mobileField = value;
                this.RaisePropertyChanged("Mobile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservice.creditsafe.se/getdata/")]
    public partial class Account : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userNameField;
        
        private string passwordField;
        
        private string transactionIdField;
        
        private LANGUAGE languageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string TransactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
                this.RaisePropertyChanged("TransactionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public LANGUAGE Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
                this.RaisePropertyChanged("Language");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservice.creditsafe.se/getdata/")]
    public enum LANGUAGE {
        
        /// <remarks/>
        EN,
        
        /// <remarks/>
        SWE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservice.creditsafe.se/getdata/")]
    public partial class ERROR : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cause_of_RejectField;
        
        private string reject_textField;
        
        private string reject_commentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Cause_of_Reject {
            get {
                return this.cause_of_RejectField;
            }
            set {
                this.cause_of_RejectField = value;
                this.RaisePropertyChanged("Cause_of_Reject");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Reject_text {
            get {
                return this.reject_textField;
            }
            set {
                this.reject_textField = value;
                this.RaisePropertyChanged("Reject_text");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Reject_comment {
            get {
                return this.reject_commentField;
            }
            set {
                this.reject_commentField = value;
                this.RaisePropertyChanged("Reject_comment");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservice.creditsafe.se/getdata/")]
    public partial class GETDATA_RESPONSE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string searchNumberField;
        
        private string transactionIdField;
        
        private ERROR errorField;
        
        private string block_NameField;
        
        private System.Data.DataSet parametersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SearchNumber {
            get {
                return this.searchNumberField;
            }
            set {
                this.searchNumberField = value;
                this.RaisePropertyChanged("SearchNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TransactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
                this.RaisePropertyChanged("TransactionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public ERROR Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("Error");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Block_Name {
            get {
                return this.block_NameField;
            }
            set {
                this.block_NameField = value;
                this.RaisePropertyChanged("Block_Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.Data.DataSet Parameters {
            get {
                return this.parametersField;
            }
            set {
                this.parametersField = value;
                this.RaisePropertyChanged("Parameters");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GetDataSoapChannel : nCreditReport.CreditSafeSeGetData.GetDataSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetDataSoapClient : System.ServiceModel.ClientBase<nCreditReport.CreditSafeSeGetData.GetDataSoap>, nCreditReport.CreditSafeSeGetData.GetDataSoap {
        
        public GetDataSoapClient() {
        }
        
        public GetDataSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetDataSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetDataSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetDataSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public nCreditReport.CreditSafeSeGetData.GETDATA_RESPONSE GetDataBySecure(nCreditReport.CreditSafeSeGetData.GETDATA_REQUEST GetData_Request) {
            return base.Channel.GetDataBySecure(GetData_Request);
        }
        
        public System.Threading.Tasks.Task<nCreditReport.CreditSafeSeGetData.GETDATA_RESPONSE> GetDataBySecureAsync(nCreditReport.CreditSafeSeGetData.GETDATA_REQUEST GetData_Request) {
            return base.Channel.GetDataBySecureAsync(GetData_Request);
        }
    }
}
