//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignicatPackagingServiceV4
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://id.signicat.com/definitions/wsdl/Packaging-v4", ConfigurationName="SignicatPackagingServiceV4.PackagingEndPoint")]
    public interface PackagingEndPoint
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SignicatPackagingServiceV4.createpackageResponse1> createpackageAsync(SignicatPackagingServiceV4.createpackage request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://id.signicat.com/definitions/wsdl/Packaging-v4")]
    public partial class createpackagerequest
    {
        
        private string versionField;
        
        private string serviceField;
        
        private string passwordField;
        
        private string validationpolicyField;
        
        private string packagingmethodField;
        
        private bool sendresulttoarchiveField;
        
        private object[] itemsField;
        
        public createpackagerequest()
        {
            this.sendresulttoarchiveField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string service
        {
            get
            {
                return this.serviceField;
            }
            set
            {
                this.serviceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("validation-policy", Order=3)]
        public string validationpolicy
        {
            get
            {
                return this.validationpolicyField;
            }
            set
            {
                this.validationpolicyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("packaging-method", Order=4)]
        public string packagingmethod
        {
            get
            {
                return this.packagingmethodField;
            }
            set
            {
                this.packagingmethodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("send-result-to-archive", Order=5)]
        public bool sendresulttoarchive
        {
            get
            {
                return this.sendresulttoarchiveField;
            }
            set
            {
                this.sendresulttoarchiveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sdo", typeof(documentid), Order=6)]
        [System.Xml.Serialization.XmlElementAttribute("sdo-extended", typeof(sdoextended), Order=6)]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="document-id", Namespace="https://id.signicat.com/definitions/wsdl/Packaging-v4")]
    public partial class documentid
    {
        
        private archivedocumentid archivedocumentidField;
        
        private orderdocumentid orderdocumentidField;
        
        private sdsdocumentid sdsdocumentidField;
        
        private string uridocumentidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("archive-document-id", Order=0)]
        public archivedocumentid archivedocumentid
        {
            get
            {
                return this.archivedocumentidField;
            }
            set
            {
                this.archivedocumentidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("order-document-id", Order=1)]
        public orderdocumentid orderdocumentid
        {
            get
            {
                return this.orderdocumentidField;
            }
            set
            {
                this.orderdocumentidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sds-document-id", Order=2)]
        public sdsdocumentid sdsdocumentid
        {
            get
            {
                return this.sdsdocumentidField;
            }
            set
            {
                this.sdsdocumentidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("uri-document-id", Order=3)]
        public string uridocumentid
        {
            get
            {
                return this.uridocumentidField;
            }
            set
            {
                this.uridocumentidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="archive-document-id", Namespace="https://id.signicat.com/definitions/wsdl/Packaging-v4")]
    public partial class archivedocumentid
    {
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://id.signicat.com/definitions/wsdl/Packaging-v4")]
    public partial class error
    {
        
        private string codeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="supplementary-data", Namespace="https://id.signicat.com/definitions/wsdl/Packaging-v4")]
    public partial class supplementarydata
    {
        
        private documentid originaldocumentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("original-document", Order=0)]
        public documentid originaldocument
        {
            get
            {
                return this.originaldocumentField;
            }
            set
            {
                this.originaldocumentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="sdo-extended", Namespace="https://id.signicat.com/definitions/wsdl/Packaging-v4")]
    public partial class sdoextended
    {
        
        private documentid sdoField;
        
        private supplementarydata supplementarydataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public documentid sdo
        {
            get
            {
                return this.sdoField;
            }
            set
            {
                this.sdoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("supplementary-data", Order=1)]
        public supplementarydata supplementarydata
        {
            get
            {
                return this.supplementarydataField;
            }
            set
            {
                this.supplementarydataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="sds-document-id", Namespace="https://id.signicat.com/definitions/wsdl/Packaging-v4")]
    public partial class sdsdocumentid
    {
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="order-document-id", Namespace="https://id.signicat.com/definitions/wsdl/Packaging-v4")]
    public partial class orderdocumentid
    {
        
        private string requestidField;
        
        private string taskidField;
        
        private string documentidField;
        
        private string typeField;
        
        public orderdocumentid()
        {
            this.typeField = "result";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("request-id", Order=0)]
        public string requestid
        {
            get
            {
                return this.requestidField;
            }
            set
            {
                this.requestidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("task-id", Order=1)]
        public string taskid
        {
            get
            {
                return this.taskidField;
            }
            set
            {
                this.taskidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("document-id", Order=2)]
        public string documentid
        {
            get
            {
                return this.documentidField;
            }
            set
            {
                this.documentidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://id.signicat.com/definitions/wsdl/Packaging-v4")]
    public partial class createpackageresponse
    {
        
        private string idField;
        
        private error errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public error error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createpackage
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="create-package-request", Namespace="https://id.signicat.com/definitions/wsdl/Packaging-v4", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("create-package-request")]
        public SignicatPackagingServiceV4.createpackagerequest createpackagerequest;
        
        public createpackage()
        {
        }
        
        public createpackage(SignicatPackagingServiceV4.createpackagerequest createpackagerequest)
        {
            this.createpackagerequest = createpackagerequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createpackageResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="create-package-response", Namespace="https://id.signicat.com/definitions/wsdl/Packaging-v4", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("create-package-response")]
        public SignicatPackagingServiceV4.createpackageresponse createpackageresponse;
        
        public createpackageResponse1()
        {
        }
        
        public createpackageResponse1(SignicatPackagingServiceV4.createpackageresponse createpackageresponse)
        {
            this.createpackageresponse = createpackageresponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface PackagingEndPointChannel : SignicatPackagingServiceV4.PackagingEndPoint, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class PackagingEndPointClient : System.ServiceModel.ClientBase<SignicatPackagingServiceV4.PackagingEndPoint>, SignicatPackagingServiceV4.PackagingEndPoint
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PackagingEndPointClient() : 
                base(PackagingEndPointClient.GetDefaultBinding(), PackagingEndPointClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.PackagingEndPointImplPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PackagingEndPointClient(EndpointConfiguration endpointConfiguration) : 
                base(PackagingEndPointClient.GetBindingForEndpoint(endpointConfiguration), PackagingEndPointClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PackagingEndPointClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PackagingEndPointClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PackagingEndPointClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PackagingEndPointClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PackagingEndPointClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SignicatPackagingServiceV4.createpackageResponse1> SignicatPackagingServiceV4.PackagingEndPoint.createpackageAsync(SignicatPackagingServiceV4.createpackage request)
        {
            return base.Channel.createpackageAsync(request);
        }
        
        public System.Threading.Tasks.Task<SignicatPackagingServiceV4.createpackageResponse1> createpackageAsync(SignicatPackagingServiceV4.createpackagerequest createpackagerequest)
        {
            SignicatPackagingServiceV4.createpackage inValue = new SignicatPackagingServiceV4.createpackage();
            inValue.createpackagerequest = createpackagerequest;
            return ((SignicatPackagingServiceV4.PackagingEndPoint)(this)).createpackageAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PackagingEndPointImplPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PackagingEndPointImplPort))
            {
                return new System.ServiceModel.EndpointAddress("https://preprod.signicat.com/ws/packagingservice-v4");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return PackagingEndPointClient.GetBindingForEndpoint(EndpointConfiguration.PackagingEndPointImplPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return PackagingEndPointClient.GetEndpointAddress(EndpointConfiguration.PackagingEndPointImplPort);
        }
        
        public enum EndpointConfiguration
        {
            
            PackagingEndPointImplPort,
        }
    }
}
