//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://certificates.vero.fi/2017/10/certificateservices", ConfigurationName="CertificateServicesPortType")]
public interface CertificateServicesPortType
{
    
    // CODEGEN: Generating message contract since the operation signNewCertificate is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute(Action="signNewCertificate", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    signNewCertificateResponse1 signNewCertificate(signNewCertificateRequest1 request);
    
    [System.ServiceModel.OperationContractAttribute(Action="signNewCertificate", ReplyAction="*")]
    System.Threading.Tasks.Task<signNewCertificateResponse1> signNewCertificateAsync(signNewCertificateRequest1 request);
    
    // CODEGEN: Generating message contract since the operation renewCertificate is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute(Action="renewCertificate", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    renewCertificateResponse1 renewCertificate(renewCertificateRequest1 request);
    
    [System.ServiceModel.OperationContractAttribute(Action="renewCertificate", ReplyAction="*")]
    System.Threading.Tasks.Task<renewCertificateResponse1> renewCertificateAsync(renewCertificateRequest1 request);
    
    // CODEGEN: Generating message contract since the operation getCertificate is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute(Action="getCertificate", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    getCertificateResponse1 getCertificate(getCertificateRequest1 request);
    
    [System.ServiceModel.OperationContractAttribute(Action="getCertificate", ReplyAction="*")]
    System.Threading.Tasks.Task<getCertificateResponse1> getCertificateAsync(getCertificateRequest1 request);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://certificates.vero.fi/2017/10/certificateservices")]
public partial class SignNewCertificateRequest
{
    
    private EnvironmentTypes environmentField;
    
    private string customerIdField;
    
    private string customerNameField;
    
    private string transferIdField;
    
    private string transferPasswordField;
    
    private byte[] certificateRequestField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public EnvironmentTypes Environment
    {
        get
        {
            return this.environmentField;
        }
        set
        {
            this.environmentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=1)]
    public string CustomerId
    {
        get
        {
            return this.customerIdField;
        }
        set
        {
            this.customerIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=2)]
    public string CustomerName
    {
        get
        {
            return this.customerNameField;
        }
        set
        {
            this.customerNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=3)]
    public string TransferId
    {
        get
        {
            return this.transferIdField;
        }
        set
        {
            this.transferIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=4)]
    public string TransferPassword
    {
        get
        {
            return this.transferPasswordField;
        }
        set
        {
            this.transferPasswordField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=5)]
    public byte[] CertificateRequest
    {
        get
        {
            return this.certificateRequestField;
        }
        set
        {
            this.certificateRequestField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://certificates.vero.fi/2017/10/certificateservices")]
public enum EnvironmentTypes
{
    
    /// <remarks/>
    PRODUCTION,
    
    /// <remarks/>
    TEST,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://certificates.vero.fi/2017/10/certificateservices")]
public partial class GetCertificateResponse
{
    
    private byte[] certificateField;
    
    private Result resultField;
    
    private SignatureType signatureField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=0)]
    public byte[] Certificate
    {
        get
        {
            return this.certificateField;
        }
        set
        {
            this.certificateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public Result Result
    {
        get
        {
            return this.resultField;
        }
        set
        {
            this.resultField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", Order=2)]
    public SignatureType Signature
    {
        get
        {
            return this.signatureField;
        }
        set
        {
            this.signatureField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://certificates.vero.fi/2017/10/certificateservices")]
public partial class Result
{
    
    private ResultTypes statusField;
    
    private ErrorType[] errorInfoField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public ResultTypes Status
    {
        get
        {
            return this.statusField;
        }
        set
        {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ErrorInfo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public ErrorType[] ErrorInfo
    {
        get
        {
            return this.errorInfoField;
        }
        set
        {
            this.errorInfoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://certificates.vero.fi/2017/10/certificateservices")]
public enum ResultTypes
{
    
    /// <remarks/>
    FAIL,
    
    /// <remarks/>
    OK,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://certificates.vero.fi/2017/10/certificateservices")]
public partial class ErrorType
{
    
    private string errorCodeField;
    
    private string errorMessageField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=0)]
    public string ErrorCode
    {
        get
        {
            return this.errorCodeField;
        }
        set
        {
            this.errorCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=1)]
    public string ErrorMessage
    {
        get
        {
            return this.errorMessageField;
        }
        set
        {
            this.errorMessageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
public partial class SignatureType
{
    
    private SignedInfoType signedInfoField;
    
    private SignatureValueType signatureValueField;
    
    private KeyInfoType keyInfoField;
    
    private ObjectType[] objectField;
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public SignedInfoType SignedInfo
    {
        get
        {
            return this.signedInfoField;
        }
        set
        {
            this.signedInfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public SignatureValueType SignatureValue
    {
        get
        {
            return this.signatureValueField;
        }
        set
        {
            this.signatureValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public KeyInfoType KeyInfo
    {
        get
        {
            return this.keyInfoField;
        }
        set
        {
            this.keyInfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Object", Order=3)]
    public ObjectType[] Object
    {
        get
        {
            return this.objectField;
        }
        set
        {
            this.objectField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string Id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
public partial class SignedInfoType
{
    
    private CanonicalizationMethodType canonicalizationMethodField;
    
    private SignatureMethodType signatureMethodField;
    
    private ReferenceType[] referenceField;
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public CanonicalizationMethodType CanonicalizationMethod
    {
        get
        {
            return this.canonicalizationMethodField;
        }
        set
        {
            this.canonicalizationMethodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public SignatureMethodType SignatureMethod
    {
        get
        {
            return this.signatureMethodField;
        }
        set
        {
            this.signatureMethodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Reference", Order=2)]
    public ReferenceType[] Reference
    {
        get
        {
            return this.referenceField;
        }
        set
        {
            this.referenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string Id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
public partial class CanonicalizationMethodType
{
    
    private System.Xml.XmlNode[] anyField;
    
    private string algorithmField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
    public System.Xml.XmlNode[] Any
    {
        get
        {
            return this.anyField;
        }
        set
        {
            this.anyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string Algorithm
    {
        get
        {
            return this.algorithmField;
        }
        set
        {
            this.algorithmField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
public partial class SignatureMethodType
{
    
    private string hMACOutputLengthField;
    
    private System.Xml.XmlNode[] anyField;
    
    private string algorithmField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
    public string HMACOutputLength
    {
        get
        {
            return this.hMACOutputLengthField;
        }
        set
        {
            this.hMACOutputLengthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    [System.Xml.Serialization.XmlAnyElementAttribute(Order=1)]
    public System.Xml.XmlNode[] Any
    {
        get
        {
            return this.anyField;
        }
        set
        {
            this.anyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string Algorithm
    {
        get
        {
            return this.algorithmField;
        }
        set
        {
            this.algorithmField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
public partial class ReferenceType
{
    
    private TransformType[] transformsField;
    
    private DigestMethodType digestMethodField;
    
    private byte[] digestValueField;
    
    private string idField;
    
    private string uRIField;
    
    private string typeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Transform", IsNullable=false)]
    public TransformType[] Transforms
    {
        get
        {
            return this.transformsField;
        }
        set
        {
            this.transformsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public DigestMethodType DigestMethod
    {
        get
        {
            return this.digestMethodField;
        }
        set
        {
            this.digestMethodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=2)]
    public byte[] DigestValue
    {
        get
        {
            return this.digestValueField;
        }
        set
        {
            this.digestValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string Id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string URI
    {
        get
        {
            return this.uRIField;
        }
        set
        {
            this.uRIField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string Type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
public partial class TransformType
{
    
    private object[] itemsField;
    
    private string[] textField;
    
    private string algorithmField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("XPath", typeof(string), Order=0)]
    public object[] Items
    {
        get
        {
            return this.itemsField;
        }
        set
        {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text
    {
        get
        {
            return this.textField;
        }
        set
        {
            this.textField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string Algorithm
    {
        get
        {
            return this.algorithmField;
        }
        set
        {
            this.algorithmField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
public partial class DigestMethodType
{
    
    private System.Xml.XmlNode[] anyField;
    
    private string algorithmField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
    public System.Xml.XmlNode[] Any
    {
        get
        {
            return this.anyField;
        }
        set
        {
            this.anyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string Algorithm
    {
        get
        {
            return this.algorithmField;
        }
        set
        {
            this.algorithmField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
public partial class SignatureValueType
{
    
    private string idField;
    
    private byte[] valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string Id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="base64Binary")]
    public byte[] Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
public partial class KeyInfoType
{
    
    private object[] itemsField;
    
    private ItemsChoiceType2[] itemsElementNameField;
    
    private string[] textField;
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("KeyName", typeof(string), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("KeyValue", typeof(KeyValueType), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("MgmtData", typeof(string), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("PGPData", typeof(PGPDataType), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("RetrievalMethod", typeof(RetrievalMethodType), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("SPKIData", typeof(SPKIDataType), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("X509Data", typeof(X509DataType), Order=0)]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items
    {
        get
        {
            return this.itemsField;
        }
        set
        {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName", Order=1)]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType2[] ItemsElementName
    {
        get
        {
            return this.itemsElementNameField;
        }
        set
        {
            this.itemsElementNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text
    {
        get
        {
            return this.textField;
        }
        set
        {
            this.textField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string Id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
public partial class KeyValueType
{
    
    private object itemField;
    
    private string[] textField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("DSAKeyValue", typeof(DSAKeyValueType), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("RSAKeyValue", typeof(RSAKeyValueType), Order=0)]
    public object Item
    {
        get
        {
            return this.itemField;
        }
        set
        {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text
    {
        get
        {
            return this.textField;
        }
        set
        {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
public partial class DSAKeyValueType
{
    
    private byte[] pField;
    
    private byte[] qField;
    
    private byte[] gField;
    
    private byte[] yField;
    
    private byte[] jField;
    
    private byte[] seedField;
    
    private byte[] pgenCounterField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=0)]
    public byte[] P
    {
        get
        {
            return this.pField;
        }
        set
        {
            this.pField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1)]
    public byte[] Q
    {
        get
        {
            return this.qField;
        }
        set
        {
            this.qField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=2)]
    public byte[] G
    {
        get
        {
            return this.gField;
        }
        set
        {
            this.gField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=3)]
    public byte[] Y
    {
        get
        {
            return this.yField;
        }
        set
        {
            this.yField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=4)]
    public byte[] J
    {
        get
        {
            return this.jField;
        }
        set
        {
            this.jField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=5)]
    public byte[] Seed
    {
        get
        {
            return this.seedField;
        }
        set
        {
            this.seedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=6)]
    public byte[] PgenCounter
    {
        get
        {
            return this.pgenCounterField;
        }
        set
        {
            this.pgenCounterField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
public partial class RSAKeyValueType
{
    
    private byte[] modulusField;
    
    private byte[] exponentField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=0)]
    public byte[] Modulus
    {
        get
        {
            return this.modulusField;
        }
        set
        {
            this.modulusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1)]
    public byte[] Exponent
    {
        get
        {
            return this.exponentField;
        }
        set
        {
            this.exponentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
public partial class PGPDataType
{
    
    private object[] itemsField;
    
    private ItemsChoiceType1[] itemsElementNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("PGPKeyID", typeof(byte[]), DataType="base64Binary", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("PGPKeyPacket", typeof(byte[]), DataType="base64Binary", Order=0)]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items
    {
        get
        {
            return this.itemsField;
        }
        set
        {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName", Order=1)]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType1[] ItemsElementName
    {
        get
        {
            return this.itemsElementNameField;
        }
        set
        {
            this.itemsElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", IncludeInSchema=false)]
public enum ItemsChoiceType1
{
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("##any:")]
    Item,
    
    /// <remarks/>
    PGPKeyID,
    
    /// <remarks/>
    PGPKeyPacket,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
public partial class RetrievalMethodType
{
    
    private TransformType[] transformsField;
    
    private string uRIField;
    
    private string typeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Transform", IsNullable=false)]
    public TransformType[] Transforms
    {
        get
        {
            return this.transformsField;
        }
        set
        {
            this.transformsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string URI
    {
        get
        {
            return this.uRIField;
        }
        set
        {
            this.uRIField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string Type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
public partial class SPKIDataType
{
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("SPKISexp", typeof(byte[]), DataType="base64Binary", Order=0)]
    public object[] Items
    {
        get
        {
            return this.itemsField;
        }
        set
        {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
public partial class X509DataType
{
    
    private object[] itemsField;
    
    private ItemsChoiceType[] itemsElementNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("X509CRL", typeof(byte[]), DataType="base64Binary", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("X509Certificate", typeof(byte[]), DataType="base64Binary", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("X509IssuerSerial", typeof(X509IssuerSerialType), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("X509SKI", typeof(byte[]), DataType="base64Binary", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("X509SubjectName", typeof(string), Order=0)]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items
    {
        get
        {
            return this.itemsField;
        }
        set
        {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName", Order=1)]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType[] ItemsElementName
    {
        get
        {
            return this.itemsElementNameField;
        }
        set
        {
            this.itemsElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
public partial class X509IssuerSerialType
{
    
    private string x509IssuerNameField;
    
    private string x509SerialNumberField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string X509IssuerName
    {
        get
        {
            return this.x509IssuerNameField;
        }
        set
        {
            this.x509IssuerNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=1)]
    public string X509SerialNumber
    {
        get
        {
            return this.x509SerialNumberField;
        }
        set
        {
            this.x509SerialNumberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", IncludeInSchema=false)]
public enum ItemsChoiceType
{
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("##any:")]
    Item,
    
    /// <remarks/>
    X509CRL,
    
    /// <remarks/>
    X509Certificate,
    
    /// <remarks/>
    X509IssuerSerial,
    
    /// <remarks/>
    X509SKI,
    
    /// <remarks/>
    X509SubjectName,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", IncludeInSchema=false)]
public enum ItemsChoiceType2
{
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("##any:")]
    Item,
    
    /// <remarks/>
    KeyName,
    
    /// <remarks/>
    KeyValue,
    
    /// <remarks/>
    MgmtData,
    
    /// <remarks/>
    PGPData,
    
    /// <remarks/>
    RetrievalMethod,
    
    /// <remarks/>
    SPKIData,
    
    /// <remarks/>
    X509Data,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
public partial class ObjectType
{
    
    private System.Xml.XmlNode[] anyField;
    
    private string idField;
    
    private string mimeTypeField;
    
    private string encodingField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
    public System.Xml.XmlNode[] Any
    {
        get
        {
            return this.anyField;
        }
        set
        {
            this.anyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string Id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string MimeType
    {
        get
        {
            return this.mimeTypeField;
        }
        set
        {
            this.mimeTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string Encoding
    {
        get
        {
            return this.encodingField;
        }
        set
        {
            this.encodingField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://certificates.vero.fi/2017/10/certificateservices")]
public partial class GetCertificateRequest
{
    
    private EnvironmentTypes environmentField;
    
    private string customerIdField;
    
    private string customerNameField;
    
    private string retrievalIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public EnvironmentTypes Environment
    {
        get
        {
            return this.environmentField;
        }
        set
        {
            this.environmentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=1)]
    public string CustomerId
    {
        get
        {
            return this.customerIdField;
        }
        set
        {
            this.customerIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=2)]
    public string CustomerName
    {
        get
        {
            return this.customerNameField;
        }
        set
        {
            this.customerNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=3)]
    public string RetrievalId
    {
        get
        {
            return this.retrievalIdField;
        }
        set
        {
            this.retrievalIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://certificates.vero.fi/2017/10/certificateservices")]
public partial class RenewCertificateResponse
{
    
    private string retrievalIdField;
    
    private Result resultField;
    
    private SignatureType signatureField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=0)]
    public string RetrievalId
    {
        get
        {
            return this.retrievalIdField;
        }
        set
        {
            this.retrievalIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public Result Result
    {
        get
        {
            return this.resultField;
        }
        set
        {
            this.resultField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", Order=2)]
    public SignatureType Signature
    {
        get
        {
            return this.signatureField;
        }
        set
        {
            this.signatureField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://certificates.vero.fi/2017/10/certificateservices")]
public partial class RenewCertificateRequest
{
    
    private EnvironmentTypes environmentField;
    
    private string customerIdField;
    
    private string customerNameField;
    
    private byte[] certificateRequestField;
    
    private SignatureType signatureField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public EnvironmentTypes Environment
    {
        get
        {
            return this.environmentField;
        }
        set
        {
            this.environmentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=1)]
    public string CustomerId
    {
        get
        {
            return this.customerIdField;
        }
        set
        {
            this.customerIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=2)]
    public string CustomerName
    {
        get
        {
            return this.customerNameField;
        }
        set
        {
            this.customerNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=3)]
    public byte[] CertificateRequest
    {
        get
        {
            return this.certificateRequestField;
        }
        set
        {
            this.certificateRequestField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", Order=4)]
    public SignatureType Signature
    {
        get
        {
            return this.signatureField;
        }
        set
        {
            this.signatureField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://certificates.vero.fi/2017/10/certificateservices")]
public partial class SignNewCertificateResponse
{
    
    private string retrievalIdField;
    
    private Result resultField;
    
    private SignatureType signatureField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="normalizedString", Order=0)]
    public string RetrievalId
    {
        get
        {
            return this.retrievalIdField;
        }
        set
        {
            this.retrievalIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public Result Result
    {
        get
        {
            return this.resultField;
        }
        set
        {
            this.resultField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", Order=2)]
    public SignatureType Signature
    {
        get
        {
            return this.signatureField;
        }
        set
        {
            this.signatureField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class signNewCertificateRequest1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://certificates.vero.fi/2017/10/certificateservices", Order=0)]
    public SignNewCertificateRequest SignNewCertificateRequest;
    
    public signNewCertificateRequest1()
    {
    }
    
    public signNewCertificateRequest1(SignNewCertificateRequest SignNewCertificateRequest)
    {
        this.SignNewCertificateRequest = SignNewCertificateRequest;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class signNewCertificateResponse1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://certificates.vero.fi/2017/10/certificateservices", Order=0)]
    public SignNewCertificateResponse SignNewCertificateResponse;
    
    public signNewCertificateResponse1()
    {
    }
    
    public signNewCertificateResponse1(SignNewCertificateResponse SignNewCertificateResponse)
    {
        this.SignNewCertificateResponse = SignNewCertificateResponse;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class renewCertificateRequest1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://certificates.vero.fi/2017/10/certificateservices", Order=0)]
    public RenewCertificateRequest RenewCertificateRequest;
    
    public renewCertificateRequest1()
    {
    }
    
    public renewCertificateRequest1(RenewCertificateRequest RenewCertificateRequest)
    {
        this.RenewCertificateRequest = RenewCertificateRequest;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class renewCertificateResponse1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://certificates.vero.fi/2017/10/certificateservices", Order=0)]
    public RenewCertificateResponse RenewCertificateResponse;
    
    public renewCertificateResponse1()
    {
    }
    
    public renewCertificateResponse1(RenewCertificateResponse RenewCertificateResponse)
    {
        this.RenewCertificateResponse = RenewCertificateResponse;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getCertificateRequest1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://certificates.vero.fi/2017/10/certificateservices", Order=0)]
    public GetCertificateRequest GetCertificateRequest;
    
    public getCertificateRequest1()
    {
    }
    
    public getCertificateRequest1(GetCertificateRequest GetCertificateRequest)
    {
        this.GetCertificateRequest = GetCertificateRequest;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getCertificateResponse1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://certificates.vero.fi/2017/10/certificateservices", Order=0)]
    public GetCertificateResponse GetCertificateResponse;
    
    public getCertificateResponse1()
    {
    }
    
    public getCertificateResponse1(GetCertificateResponse GetCertificateResponse)
    {
        this.GetCertificateResponse = GetCertificateResponse;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface CertificateServicesPortTypeChannel : CertificateServicesPortType, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class CertificateServicesPortTypeClient : System.ServiceModel.ClientBase<CertificateServicesPortType>, CertificateServicesPortType
{
    
    public CertificateServicesPortTypeClient()
    {
    }
    
    public CertificateServicesPortTypeClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public CertificateServicesPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CertificateServicesPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CertificateServicesPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    signNewCertificateResponse1 CertificateServicesPortType.signNewCertificate(signNewCertificateRequest1 request)
    {
        return base.Channel.signNewCertificate(request);
    }
    
    public SignNewCertificateResponse signNewCertificate(SignNewCertificateRequest SignNewCertificateRequest)
    {
        signNewCertificateRequest1 inValue = new signNewCertificateRequest1();
        inValue.SignNewCertificateRequest = SignNewCertificateRequest;
        signNewCertificateResponse1 retVal = ((CertificateServicesPortType)(this)).signNewCertificate(inValue);
        return retVal.SignNewCertificateResponse;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<signNewCertificateResponse1> CertificateServicesPortType.signNewCertificateAsync(signNewCertificateRequest1 request)
    {
        return base.Channel.signNewCertificateAsync(request);
    }
    
    public System.Threading.Tasks.Task<signNewCertificateResponse1> signNewCertificateAsync(SignNewCertificateRequest SignNewCertificateRequest)
    {
        signNewCertificateRequest1 inValue = new signNewCertificateRequest1();
        inValue.SignNewCertificateRequest = SignNewCertificateRequest;
        return ((CertificateServicesPortType)(this)).signNewCertificateAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    renewCertificateResponse1 CertificateServicesPortType.renewCertificate(renewCertificateRequest1 request)
    {
        return base.Channel.renewCertificate(request);
    }
    
    public RenewCertificateResponse renewCertificate(RenewCertificateRequest RenewCertificateRequest)
    {
        renewCertificateRequest1 inValue = new renewCertificateRequest1();
        inValue.RenewCertificateRequest = RenewCertificateRequest;
        renewCertificateResponse1 retVal = ((CertificateServicesPortType)(this)).renewCertificate(inValue);
        return retVal.RenewCertificateResponse;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<renewCertificateResponse1> CertificateServicesPortType.renewCertificateAsync(renewCertificateRequest1 request)
    {
        return base.Channel.renewCertificateAsync(request);
    }
    
    public System.Threading.Tasks.Task<renewCertificateResponse1> renewCertificateAsync(RenewCertificateRequest RenewCertificateRequest)
    {
        renewCertificateRequest1 inValue = new renewCertificateRequest1();
        inValue.RenewCertificateRequest = RenewCertificateRequest;
        return ((CertificateServicesPortType)(this)).renewCertificateAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    getCertificateResponse1 CertificateServicesPortType.getCertificate(getCertificateRequest1 request)
    {
        return base.Channel.getCertificate(request);
    }
    
    public GetCertificateResponse getCertificate(GetCertificateRequest GetCertificateRequest)
    {
        getCertificateRequest1 inValue = new getCertificateRequest1();
        inValue.GetCertificateRequest = GetCertificateRequest;
        getCertificateResponse1 retVal = ((CertificateServicesPortType)(this)).getCertificate(inValue);
        return retVal.GetCertificateResponse;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<getCertificateResponse1> CertificateServicesPortType.getCertificateAsync(getCertificateRequest1 request)
    {
        return base.Channel.getCertificateAsync(request);
    }
    
    public System.Threading.Tasks.Task<getCertificateResponse1> getCertificateAsync(GetCertificateRequest GetCertificateRequest)
    {
        getCertificateRequest1 inValue = new getCertificateRequest1();
        inValue.GetCertificateRequest = GetCertificateRequest;
        return ((CertificateServicesPortType)(this)).getCertificateAsync(inValue);
    }
}
