//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nCreditReport.CreditSafeSeCreditApproval {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CAS_PERSON_REQUEST", Namespace="https://webservice.creditsafe.se/CAS/")]
    [System.SerializableAttribute()]
    public partial class CAS_PERSON_REQUEST : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private nCreditReport.CreditSafeSeCreditApproval.Account accountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SearchNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZIPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TownField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TemplatesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LODCustFreeTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public nCreditReport.CreditSafeSeCreditApproval.Account account {
            get {
                return this.accountField;
            }
            set {
                if ((object.ReferenceEquals(this.accountField, value) != true)) {
                    this.accountField = value;
                    this.RaisePropertyChanged("account");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string SearchNumber {
            get {
                return this.SearchNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.SearchNumberField, value) != true)) {
                    this.SearchNumberField = value;
                    this.RaisePropertyChanged("SearchNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Address1 {
            get {
                return this.Address1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address1Field, value) != true)) {
                    this.Address1Field = value;
                    this.RaisePropertyChanged("Address1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string ZIP {
            get {
                return this.ZIPField;
            }
            set {
                if ((object.ReferenceEquals(this.ZIPField, value) != true)) {
                    this.ZIPField = value;
                    this.RaisePropertyChanged("ZIP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Town {
            get {
                return this.TownField;
            }
            set {
                if ((object.ReferenceEquals(this.TownField, value) != true)) {
                    this.TownField = value;
                    this.RaisePropertyChanged("Town");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Templates {
            get {
                return this.TemplatesField;
            }
            set {
                if ((object.ReferenceEquals(this.TemplatesField, value) != true)) {
                    this.TemplatesField = value;
                    this.RaisePropertyChanged("Templates");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string LODCustFreeText {
            get {
                return this.LODCustFreeTextField;
            }
            set {
                if ((object.ReferenceEquals(this.LODCustFreeTextField, value) != true)) {
                    this.LODCustFreeTextField = value;
                    this.RaisePropertyChanged("LODCustFreeText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Mobile {
            get {
                return this.MobileField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileField, value) != true)) {
                    this.MobileField = value;
                    this.RaisePropertyChanged("Mobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Account", Namespace="https://webservice.creditsafe.se/CAS/")]
    [System.SerializableAttribute()]
    public partial class Account : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionIdField;
        
        private nCreditReport.CreditSafeSeCreditApproval.LANGUAGE LanguageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string TransactionId {
            get {
                return this.TransactionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionIdField, value) != true)) {
                    this.TransactionIdField = value;
                    this.RaisePropertyChanged("TransactionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public nCreditReport.CreditSafeSeCreditApproval.LANGUAGE Language {
            get {
                return this.LanguageField;
            }
            set {
                if ((this.LanguageField.Equals(value) != true)) {
                    this.LanguageField = value;
                    this.RaisePropertyChanged("Language");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LANGUAGE", Namespace="https://webservice.creditsafe.se/CAS/")]
    public enum LANGUAGE : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EN = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SWE = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CAS_PERSON_RESPONSE", Namespace="https://webservice.creditsafe.se/CAS/")]
    [System.SerializableAttribute()]
    public partial class CAS_PERSON_RESPONSE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PersonnrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TemplateNamesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Status_TextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private nCreditReport.CreditSafeSeCreditApproval.ERROR[] ErrorListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GivenNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CoAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegisteredAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZIPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TownField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Personnr {
            get {
                return this.PersonnrField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonnrField, value) != true)) {
                    this.PersonnrField = value;
                    this.RaisePropertyChanged("Personnr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TemplateNames {
            get {
                return this.TemplateNamesField;
            }
            set {
                if ((object.ReferenceEquals(this.TemplateNamesField, value) != true)) {
                    this.TemplateNamesField = value;
                    this.RaisePropertyChanged("TemplateNames");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TransactionId {
            get {
                return this.TransactionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionIdField, value) != true)) {
                    this.TransactionIdField = value;
                    this.RaisePropertyChanged("TransactionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Status_Text {
            get {
                return this.Status_TextField;
            }
            set {
                if ((object.ReferenceEquals(this.Status_TextField, value) != true)) {
                    this.Status_TextField = value;
                    this.RaisePropertyChanged("Status_Text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public nCreditReport.CreditSafeSeCreditApproval.ERROR[] ErrorList {
            get {
                return this.ErrorListField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorListField, value) != true)) {
                    this.ErrorListField = value;
                    this.RaisePropertyChanged("ErrorList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string GivenName {
            get {
                return this.GivenNameField;
            }
            set {
                if ((object.ReferenceEquals(this.GivenNameField, value) != true)) {
                    this.GivenNameField = value;
                    this.RaisePropertyChanged("GivenName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string CoAddress {
            get {
                return this.CoAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.CoAddressField, value) != true)) {
                    this.CoAddressField = value;
                    this.RaisePropertyChanged("CoAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string RegisteredAddress {
            get {
                return this.RegisteredAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.RegisteredAddressField, value) != true)) {
                    this.RegisteredAddressField = value;
                    this.RaisePropertyChanged("RegisteredAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string ZIP {
            get {
                return this.ZIPField;
            }
            set {
                if ((object.ReferenceEquals(this.ZIPField, value) != true)) {
                    this.ZIPField = value;
                    this.RaisePropertyChanged("ZIP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string Town {
            get {
                return this.TownField;
            }
            set {
                if ((object.ReferenceEquals(this.TownField, value) != true)) {
                    this.TownField = value;
                    this.RaisePropertyChanged("Town");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ERROR", Namespace="https://webservice.creditsafe.se/CAS/")]
    [System.SerializableAttribute()]
    public partial class ERROR : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Cause_of_RejectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Reject_textField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Reject_commentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Cause_of_Reject {
            get {
                return this.Cause_of_RejectField;
            }
            set {
                if ((object.ReferenceEquals(this.Cause_of_RejectField, value) != true)) {
                    this.Cause_of_RejectField = value;
                    this.RaisePropertyChanged("Cause_of_Reject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Reject_text {
            get {
                return this.Reject_textField;
            }
            set {
                if ((object.ReferenceEquals(this.Reject_textField, value) != true)) {
                    this.Reject_textField = value;
                    this.RaisePropertyChanged("Reject_text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Reject_comment {
            get {
                return this.Reject_commentField;
            }
            set {
                if ((object.ReferenceEquals(this.Reject_commentField, value) != true)) {
                    this.Reject_commentField = value;
                    this.RaisePropertyChanged("Reject_comment");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CAS_COMPANY_REQUEST", Namespace="https://webservice.creditsafe.se/CAS/")]
    [System.SerializableAttribute()]
    public partial class CAS_COMPANY_REQUEST : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private nCreditReport.CreditSafeSeCreditApproval.Account accountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SearchNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZIPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TownField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TemplatesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LODCustFreeTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public nCreditReport.CreditSafeSeCreditApproval.Account account {
            get {
                return this.accountField;
            }
            set {
                if ((object.ReferenceEquals(this.accountField, value) != true)) {
                    this.accountField = value;
                    this.RaisePropertyChanged("account");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string SearchNumber {
            get {
                return this.SearchNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.SearchNumberField, value) != true)) {
                    this.SearchNumberField = value;
                    this.RaisePropertyChanged("SearchNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Address1 {
            get {
                return this.Address1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address1Field, value) != true)) {
                    this.Address1Field = value;
                    this.RaisePropertyChanged("Address1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ZIP {
            get {
                return this.ZIPField;
            }
            set {
                if ((object.ReferenceEquals(this.ZIPField, value) != true)) {
                    this.ZIPField = value;
                    this.RaisePropertyChanged("ZIP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Town {
            get {
                return this.TownField;
            }
            set {
                if ((object.ReferenceEquals(this.TownField, value) != true)) {
                    this.TownField = value;
                    this.RaisePropertyChanged("Town");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Templates {
            get {
                return this.TemplatesField;
            }
            set {
                if ((object.ReferenceEquals(this.TemplatesField, value) != true)) {
                    this.TemplatesField = value;
                    this.RaisePropertyChanged("Templates");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string LODCustFreeText {
            get {
                return this.LODCustFreeTextField;
            }
            set {
                if ((object.ReferenceEquals(this.LODCustFreeTextField, value) != true)) {
                    this.LODCustFreeTextField = value;
                    this.RaisePropertyChanged("LODCustFreeText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Mobile {
            get {
                return this.MobileField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileField, value) != true)) {
                    this.MobileField = value;
                    this.RaisePropertyChanged("Mobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CAS_COMPANY_RESPONSE", Namespace="https://webservice.creditsafe.se/CAS/")]
    [System.SerializableAttribute()]
    public partial class CAS_COMPANY_RESPONSE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Org_nrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TemplateNamesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Status_TextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private nCreditReport.CreditSafeSeCreditApproval.ERROR[] ErrorListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZIPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TownField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Org_nr {
            get {
                return this.Org_nrField;
            }
            set {
                if ((object.ReferenceEquals(this.Org_nrField, value) != true)) {
                    this.Org_nrField = value;
                    this.RaisePropertyChanged("Org_nr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TemplateNames {
            get {
                return this.TemplateNamesField;
            }
            set {
                if ((object.ReferenceEquals(this.TemplateNamesField, value) != true)) {
                    this.TemplateNamesField = value;
                    this.RaisePropertyChanged("TemplateNames");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TransactionId {
            get {
                return this.TransactionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionIdField, value) != true)) {
                    this.TransactionIdField = value;
                    this.RaisePropertyChanged("TransactionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Status_Text {
            get {
                return this.Status_TextField;
            }
            set {
                if ((object.ReferenceEquals(this.Status_TextField, value) != true)) {
                    this.Status_TextField = value;
                    this.RaisePropertyChanged("Status_Text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public nCreditReport.CreditSafeSeCreditApproval.ERROR[] ErrorList {
            get {
                return this.ErrorListField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorListField, value) != true)) {
                    this.ErrorListField = value;
                    this.RaisePropertyChanged("ErrorList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string ZIP {
            get {
                return this.ZIPField;
            }
            set {
                if ((object.ReferenceEquals(this.ZIPField, value) != true)) {
                    this.ZIPField = value;
                    this.RaisePropertyChanged("ZIP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Town {
            get {
                return this.TownField;
            }
            set {
                if ((object.ReferenceEquals(this.TownField, value) != true)) {
                    this.TownField = value;
                    this.RaisePropertyChanged("Town");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CAS_SERVICE_REQUEST", Namespace="https://webservice.creditsafe.se/CAS/")]
    [System.SerializableAttribute()]
    public partial class CAS_SERVICE_REQUEST : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private nCreditReport.CreditSafeSeCreditApproval.Account AccountField;
        
        private nCreditReport.CreditSafeSeCreditApproval.SERVICE_REPORTTYPE ReportTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public nCreditReport.CreditSafeSeCreditApproval.Account Account {
            get {
                return this.AccountField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountField, value) != true)) {
                    this.AccountField = value;
                    this.RaisePropertyChanged("Account");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public nCreditReport.CreditSafeSeCreditApproval.SERVICE_REPORTTYPE ReportType {
            get {
                return this.ReportTypeField;
            }
            set {
                if ((this.ReportTypeField.Equals(value) != true)) {
                    this.ReportTypeField = value;
                    this.RaisePropertyChanged("ReportType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SERVICE_REPORTTYPE", Namespace="https://webservice.creditsafe.se/CAS/")]
    public enum SERVICE_REPORTTYPE : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotSet = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Company = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Consumer = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CAS_SERVICE_RESPONSE", Namespace="https://webservice.creditsafe.se/CAS/")]
    [System.SerializableAttribute()]
    public partial class CAS_SERVICE_RESPONSE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private nCreditReport.CreditSafeSeCreditApproval.ERROR errorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private nCreditReport.CreditSafeSeCreditApproval.Template[] templatesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public nCreditReport.CreditSafeSeCreditApproval.ERROR error {
            get {
                return this.errorField;
            }
            set {
                if ((object.ReferenceEquals(this.errorField, value) != true)) {
                    this.errorField = value;
                    this.RaisePropertyChanged("error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public nCreditReport.CreditSafeSeCreditApproval.Template[] templates {
            get {
                return this.templatesField;
            }
            set {
                if ((object.ReferenceEquals(this.templatesField, value) != true)) {
                    this.templatesField = value;
                    this.RaisePropertyChanged("templates");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string TransactionId {
            get {
                return this.TransactionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionIdField, value) != true)) {
                    this.TransactionIdField = value;
                    this.RaisePropertyChanged("TransactionId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Template", Namespace="https://webservice.creditsafe.se/CAS/")]
    [System.SerializableAttribute()]
    public partial class Template : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TemplateNameField;
        
        private nCreditReport.CreditSafeSeCreditApproval.SERVICE_REPORTTYPE ReportTypeField;
        
        private bool ValidateAddressField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TemplateName {
            get {
                return this.TemplateNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TemplateNameField, value) != true)) {
                    this.TemplateNameField = value;
                    this.RaisePropertyChanged("TemplateName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public nCreditReport.CreditSafeSeCreditApproval.SERVICE_REPORTTYPE ReportType {
            get {
                return this.ReportTypeField;
            }
            set {
                if ((this.ReportTypeField.Equals(value) != true)) {
                    this.ReportTypeField = value;
                    this.RaisePropertyChanged("ReportType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public bool ValidateAddress {
            get {
                return this.ValidateAddressField;
            }
            set {
                if ((this.ValidateAddressField.Equals(value) != true)) {
                    this.ValidateAddressField = value;
                    this.RaisePropertyChanged("ValidateAddress");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://webservice.creditsafe.se/CAS/", ConfigurationName="CreditSafeSeCreditApproval.Cas_ServiceSoap")]
    public interface Cas_ServiceSoap {
        
        // CODEGEN: Generating message contract since element name cas_person from namespace https://webservice.creditsafe.se/CAS/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://webservice.creditsafe.se/CAS/CasPersonService", ReplyAction="*")]
        nCreditReport.CreditSafeSeCreditApproval.CasPersonServiceResponse CasPersonService(nCreditReport.CreditSafeSeCreditApproval.CasPersonServiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://webservice.creditsafe.se/CAS/CasPersonService", ReplyAction="*")]
        System.Threading.Tasks.Task<nCreditReport.CreditSafeSeCreditApproval.CasPersonServiceResponse> CasPersonServiceAsync(nCreditReport.CreditSafeSeCreditApproval.CasPersonServiceRequest request);
        
        // CODEGEN: Generating message contract since element name cas_company from namespace https://webservice.creditsafe.se/CAS/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://webservice.creditsafe.se/CAS/CasCompanyService", ReplyAction="*")]
        nCreditReport.CreditSafeSeCreditApproval.CasCompanyServiceResponse CasCompanyService(nCreditReport.CreditSafeSeCreditApproval.CasCompanyServiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://webservice.creditsafe.se/CAS/CasCompanyService", ReplyAction="*")]
        System.Threading.Tasks.Task<nCreditReport.CreditSafeSeCreditApproval.CasCompanyServiceResponse> CasCompanyServiceAsync(nCreditReport.CreditSafeSeCreditApproval.CasCompanyServiceRequest request);
        
        // CODEGEN: Generating message contract since element name cas_service from namespace https://webservice.creditsafe.se/CAS/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://webservice.creditsafe.se/CAS/GetTemplateList", ReplyAction="*")]
        nCreditReport.CreditSafeSeCreditApproval.GetTemplateListResponse GetTemplateList(nCreditReport.CreditSafeSeCreditApproval.GetTemplateListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://webservice.creditsafe.se/CAS/GetTemplateList", ReplyAction="*")]
        System.Threading.Tasks.Task<nCreditReport.CreditSafeSeCreditApproval.GetTemplateListResponse> GetTemplateListAsync(nCreditReport.CreditSafeSeCreditApproval.GetTemplateListRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CasPersonServiceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CasPersonService", Namespace="https://webservice.creditsafe.se/CAS/", Order=0)]
        public nCreditReport.CreditSafeSeCreditApproval.CasPersonServiceRequestBody Body;
        
        public CasPersonServiceRequest() {
        }
        
        public CasPersonServiceRequest(nCreditReport.CreditSafeSeCreditApproval.CasPersonServiceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://webservice.creditsafe.se/CAS/")]
    public partial class CasPersonServiceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public nCreditReport.CreditSafeSeCreditApproval.CAS_PERSON_REQUEST cas_person;
        
        public CasPersonServiceRequestBody() {
        }
        
        public CasPersonServiceRequestBody(nCreditReport.CreditSafeSeCreditApproval.CAS_PERSON_REQUEST cas_person) {
            this.cas_person = cas_person;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CasPersonServiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CasPersonServiceResponse", Namespace="https://webservice.creditsafe.se/CAS/", Order=0)]
        public nCreditReport.CreditSafeSeCreditApproval.CasPersonServiceResponseBody Body;
        
        public CasPersonServiceResponse() {
        }
        
        public CasPersonServiceResponse(nCreditReport.CreditSafeSeCreditApproval.CasPersonServiceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://webservice.creditsafe.se/CAS/")]
    public partial class CasPersonServiceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public nCreditReport.CreditSafeSeCreditApproval.CAS_PERSON_RESPONSE CasPersonServiceResult;
        
        public CasPersonServiceResponseBody() {
        }
        
        public CasPersonServiceResponseBody(nCreditReport.CreditSafeSeCreditApproval.CAS_PERSON_RESPONSE CasPersonServiceResult) {
            this.CasPersonServiceResult = CasPersonServiceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CasCompanyServiceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CasCompanyService", Namespace="https://webservice.creditsafe.se/CAS/", Order=0)]
        public nCreditReport.CreditSafeSeCreditApproval.CasCompanyServiceRequestBody Body;
        
        public CasCompanyServiceRequest() {
        }
        
        public CasCompanyServiceRequest(nCreditReport.CreditSafeSeCreditApproval.CasCompanyServiceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://webservice.creditsafe.se/CAS/")]
    public partial class CasCompanyServiceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public nCreditReport.CreditSafeSeCreditApproval.CAS_COMPANY_REQUEST cas_company;
        
        public CasCompanyServiceRequestBody() {
        }
        
        public CasCompanyServiceRequestBody(nCreditReport.CreditSafeSeCreditApproval.CAS_COMPANY_REQUEST cas_company) {
            this.cas_company = cas_company;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CasCompanyServiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CasCompanyServiceResponse", Namespace="https://webservice.creditsafe.se/CAS/", Order=0)]
        public nCreditReport.CreditSafeSeCreditApproval.CasCompanyServiceResponseBody Body;
        
        public CasCompanyServiceResponse() {
        }
        
        public CasCompanyServiceResponse(nCreditReport.CreditSafeSeCreditApproval.CasCompanyServiceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://webservice.creditsafe.se/CAS/")]
    public partial class CasCompanyServiceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public nCreditReport.CreditSafeSeCreditApproval.CAS_COMPANY_RESPONSE CasCompanyServiceResult;
        
        public CasCompanyServiceResponseBody() {
        }
        
        public CasCompanyServiceResponseBody(nCreditReport.CreditSafeSeCreditApproval.CAS_COMPANY_RESPONSE CasCompanyServiceResult) {
            this.CasCompanyServiceResult = CasCompanyServiceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTemplateListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTemplateList", Namespace="https://webservice.creditsafe.se/CAS/", Order=0)]
        public nCreditReport.CreditSafeSeCreditApproval.GetTemplateListRequestBody Body;
        
        public GetTemplateListRequest() {
        }
        
        public GetTemplateListRequest(nCreditReport.CreditSafeSeCreditApproval.GetTemplateListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://webservice.creditsafe.se/CAS/")]
    public partial class GetTemplateListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public nCreditReport.CreditSafeSeCreditApproval.CAS_SERVICE_REQUEST cas_service;
        
        public GetTemplateListRequestBody() {
        }
        
        public GetTemplateListRequestBody(nCreditReport.CreditSafeSeCreditApproval.CAS_SERVICE_REQUEST cas_service) {
            this.cas_service = cas_service;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTemplateListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTemplateListResponse", Namespace="https://webservice.creditsafe.se/CAS/", Order=0)]
        public nCreditReport.CreditSafeSeCreditApproval.GetTemplateListResponseBody Body;
        
        public GetTemplateListResponse() {
        }
        
        public GetTemplateListResponse(nCreditReport.CreditSafeSeCreditApproval.GetTemplateListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://webservice.creditsafe.se/CAS/")]
    public partial class GetTemplateListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public nCreditReport.CreditSafeSeCreditApproval.CAS_SERVICE_RESPONSE GetTemplateListResult;
        
        public GetTemplateListResponseBody() {
        }
        
        public GetTemplateListResponseBody(nCreditReport.CreditSafeSeCreditApproval.CAS_SERVICE_RESPONSE GetTemplateListResult) {
            this.GetTemplateListResult = GetTemplateListResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Cas_ServiceSoapChannel : nCreditReport.CreditSafeSeCreditApproval.Cas_ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Cas_ServiceSoapClient : System.ServiceModel.ClientBase<nCreditReport.CreditSafeSeCreditApproval.Cas_ServiceSoap>, nCreditReport.CreditSafeSeCreditApproval.Cas_ServiceSoap {
        
        public Cas_ServiceSoapClient() {
        }
        
        public Cas_ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Cas_ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Cas_ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Cas_ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        nCreditReport.CreditSafeSeCreditApproval.CasPersonServiceResponse nCreditReport.CreditSafeSeCreditApproval.Cas_ServiceSoap.CasPersonService(nCreditReport.CreditSafeSeCreditApproval.CasPersonServiceRequest request) {
            return base.Channel.CasPersonService(request);
        }
        
        public nCreditReport.CreditSafeSeCreditApproval.CAS_PERSON_RESPONSE CasPersonService(nCreditReport.CreditSafeSeCreditApproval.CAS_PERSON_REQUEST cas_person) {
            nCreditReport.CreditSafeSeCreditApproval.CasPersonServiceRequest inValue = new nCreditReport.CreditSafeSeCreditApproval.CasPersonServiceRequest();
            inValue.Body = new nCreditReport.CreditSafeSeCreditApproval.CasPersonServiceRequestBody();
            inValue.Body.cas_person = cas_person;
            nCreditReport.CreditSafeSeCreditApproval.CasPersonServiceResponse retVal = ((nCreditReport.CreditSafeSeCreditApproval.Cas_ServiceSoap)(this)).CasPersonService(inValue);
            return retVal.Body.CasPersonServiceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<nCreditReport.CreditSafeSeCreditApproval.CasPersonServiceResponse> nCreditReport.CreditSafeSeCreditApproval.Cas_ServiceSoap.CasPersonServiceAsync(nCreditReport.CreditSafeSeCreditApproval.CasPersonServiceRequest request) {
            return base.Channel.CasPersonServiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<nCreditReport.CreditSafeSeCreditApproval.CasPersonServiceResponse> CasPersonServiceAsync(nCreditReport.CreditSafeSeCreditApproval.CAS_PERSON_REQUEST cas_person) {
            nCreditReport.CreditSafeSeCreditApproval.CasPersonServiceRequest inValue = new nCreditReport.CreditSafeSeCreditApproval.CasPersonServiceRequest();
            inValue.Body = new nCreditReport.CreditSafeSeCreditApproval.CasPersonServiceRequestBody();
            inValue.Body.cas_person = cas_person;
            return ((nCreditReport.CreditSafeSeCreditApproval.Cas_ServiceSoap)(this)).CasPersonServiceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        nCreditReport.CreditSafeSeCreditApproval.CasCompanyServiceResponse nCreditReport.CreditSafeSeCreditApproval.Cas_ServiceSoap.CasCompanyService(nCreditReport.CreditSafeSeCreditApproval.CasCompanyServiceRequest request) {
            return base.Channel.CasCompanyService(request);
        }
        
        public nCreditReport.CreditSafeSeCreditApproval.CAS_COMPANY_RESPONSE CasCompanyService(nCreditReport.CreditSafeSeCreditApproval.CAS_COMPANY_REQUEST cas_company) {
            nCreditReport.CreditSafeSeCreditApproval.CasCompanyServiceRequest inValue = new nCreditReport.CreditSafeSeCreditApproval.CasCompanyServiceRequest();
            inValue.Body = new nCreditReport.CreditSafeSeCreditApproval.CasCompanyServiceRequestBody();
            inValue.Body.cas_company = cas_company;
            nCreditReport.CreditSafeSeCreditApproval.CasCompanyServiceResponse retVal = ((nCreditReport.CreditSafeSeCreditApproval.Cas_ServiceSoap)(this)).CasCompanyService(inValue);
            return retVal.Body.CasCompanyServiceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<nCreditReport.CreditSafeSeCreditApproval.CasCompanyServiceResponse> nCreditReport.CreditSafeSeCreditApproval.Cas_ServiceSoap.CasCompanyServiceAsync(nCreditReport.CreditSafeSeCreditApproval.CasCompanyServiceRequest request) {
            return base.Channel.CasCompanyServiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<nCreditReport.CreditSafeSeCreditApproval.CasCompanyServiceResponse> CasCompanyServiceAsync(nCreditReport.CreditSafeSeCreditApproval.CAS_COMPANY_REQUEST cas_company) {
            nCreditReport.CreditSafeSeCreditApproval.CasCompanyServiceRequest inValue = new nCreditReport.CreditSafeSeCreditApproval.CasCompanyServiceRequest();
            inValue.Body = new nCreditReport.CreditSafeSeCreditApproval.CasCompanyServiceRequestBody();
            inValue.Body.cas_company = cas_company;
            return ((nCreditReport.CreditSafeSeCreditApproval.Cas_ServiceSoap)(this)).CasCompanyServiceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        nCreditReport.CreditSafeSeCreditApproval.GetTemplateListResponse nCreditReport.CreditSafeSeCreditApproval.Cas_ServiceSoap.GetTemplateList(nCreditReport.CreditSafeSeCreditApproval.GetTemplateListRequest request) {
            return base.Channel.GetTemplateList(request);
        }
        
        public nCreditReport.CreditSafeSeCreditApproval.CAS_SERVICE_RESPONSE GetTemplateList(nCreditReport.CreditSafeSeCreditApproval.CAS_SERVICE_REQUEST cas_service) {
            nCreditReport.CreditSafeSeCreditApproval.GetTemplateListRequest inValue = new nCreditReport.CreditSafeSeCreditApproval.GetTemplateListRequest();
            inValue.Body = new nCreditReport.CreditSafeSeCreditApproval.GetTemplateListRequestBody();
            inValue.Body.cas_service = cas_service;
            nCreditReport.CreditSafeSeCreditApproval.GetTemplateListResponse retVal = ((nCreditReport.CreditSafeSeCreditApproval.Cas_ServiceSoap)(this)).GetTemplateList(inValue);
            return retVal.Body.GetTemplateListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<nCreditReport.CreditSafeSeCreditApproval.GetTemplateListResponse> nCreditReport.CreditSafeSeCreditApproval.Cas_ServiceSoap.GetTemplateListAsync(nCreditReport.CreditSafeSeCreditApproval.GetTemplateListRequest request) {
            return base.Channel.GetTemplateListAsync(request);
        }
        
        public System.Threading.Tasks.Task<nCreditReport.CreditSafeSeCreditApproval.GetTemplateListResponse> GetTemplateListAsync(nCreditReport.CreditSafeSeCreditApproval.CAS_SERVICE_REQUEST cas_service) {
            nCreditReport.CreditSafeSeCreditApproval.GetTemplateListRequest inValue = new nCreditReport.CreditSafeSeCreditApproval.GetTemplateListRequest();
            inValue.Body = new nCreditReport.CreditSafeSeCreditApproval.GetTemplateListRequestBody();
            inValue.Body.cas_service = cas_service;
            return ((nCreditReport.CreditSafeSeCreditApproval.Cas_ServiceSoap)(this)).GetTemplateListAsync(inValue);
        }
    }
}
