//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace nCredit.Code.Uc.CreditRegistry {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.uc.se/integration/schema/external/sharkV2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.uc.se/integration/schema/external/sharkV2", IsNullable=false)]
    public partial class CreditRegister {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DeliveryInfo", typeof(CreditRegisterDeliveryInfo))]
        [System.Xml.Serialization.XmlElementAttribute("NoDeliveryToday", typeof(CreditRegisterNoDeliveryToday))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.uc.se/integration/schema/external/sharkV2")]
    public partial class CreditRegisterDeliveryInfo {
        
        private CreditRegisterDeliveryInfoContact[] contactInfoField;
        
        private CreditRegisterDeliveryInfoCreditContracts[] creditContractsField;
        
        private string creditorIDField;
        
        private string sourceSystemIDField;
        
        private string deliveryUniqueIDField;
        
        private System.DateTime deliveryTimeStampField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("contact", IsNullable=false)]
        public CreditRegisterDeliveryInfoContact[] ContactInfo {
            get {
                return this.contactInfoField;
            }
            set {
                this.contactInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CreditContracts")]
        public CreditRegisterDeliveryInfoCreditContracts[] CreditContracts {
            get {
                return this.creditContractsField;
            }
            set {
                this.creditContractsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string creditorID {
            get {
                return this.creditorIDField;
            }
            set {
                this.creditorIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string sourceSystemID {
            get {
                return this.sourceSystemIDField;
            }
            set {
                this.sourceSystemIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string deliveryUniqueID {
            get {
                return this.deliveryUniqueIDField;
            }
            set {
                this.deliveryUniqueIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public System.DateTime deliveryTimeStamp {
            get {
                return this.deliveryTimeStampField;
            }
            set {
                this.deliveryTimeStampField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.uc.se/integration/schema/external/sharkV2")]
    public partial class CreditRegisterDeliveryInfoContact {
        
        private string creditorIDField;
        
        private Update_ST updateField;
        
        private ContactType_ST typeField;
        
        private bool typeFieldSpecified;
        
        private string emailField;
        
        private string mobileField;
        
        private string phoneField;
        
        private string roleField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string creditorID {
            get {
                return this.creditorIDField;
            }
            set {
                this.creditorIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public Update_ST update {
            get {
                return this.updateField;
            }
            set {
                this.updateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public ContactType_ST type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool typeSpecified {
            get {
                return this.typeFieldSpecified;
            }
            set {
                this.typeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string mobile {
            get {
                return this.mobileField;
            }
            set {
                this.mobileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string role {
            get {
                return this.roleField;
            }
            set {
                this.roleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.uc.se/integration/schema/external/sharkV2")]
    public enum Update_ST {
        
        /// <remarks/>
        @new,
        
        /// <remarks/>
        update,
        
        /// <remarks/>
        delete,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.uc.se/integration/schema/external/sharkV2")]
    public enum ContactType_ST {
        
        /// <remarks/>
        Function,
        
        /// <remarks/>
        Person,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.uc.se/integration/schema/external/sharkV2")]
    public partial class CreditRegisterDeliveryInfoCreditContracts {
        
        private CreditRegisterDeliveryInfoCreditContractsContract[] contractField;
        
        private string groupIDField;
        
        private string creditorIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Contract")]
        public CreditRegisterDeliveryInfoCreditContractsContract[] Contract {
            get {
                return this.contractField;
            }
            set {
                this.contractField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string groupID {
            get {
                return this.groupIDField;
            }
            set {
                this.groupIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string creditorID {
            get {
                return this.creditorIDField;
            }
            set {
                this.creditorIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.uc.se/integration/schema/external/sharkV2")]
    public partial class CreditRegisterDeliveryInfoCreditContractsContract {
        
        private CreditRegisterDeliveryInfoCreditContractsContractAccountNum accountNumField;
        
        private CreditRegisterDeliveryInfoCreditContractsContractObjectID objectIDField;
        
        private CreditRegisterDeliveryInfoCreditContractsContractBalance balanceField;
        
        private CreditRegisterDeliveryInfoCreditContractsContractAuxInfo auxInfoField;
        
        private System.DateTime startDateField;
        
        private System.DateTime endDateField;
        
        private bool endDateFieldSpecified;
        
        private Remark_ST remarkField;
        
        private bool remarkFieldSpecified;
        
        /// <remarks/>
        public CreditRegisterDeliveryInfoCreditContractsContractAccountNum accountNum {
            get {
                return this.accountNumField;
            }
            set {
                this.accountNumField = value;
            }
        }
        
        /// <remarks/>
        public CreditRegisterDeliveryInfoCreditContractsContractObjectID objectID {
            get {
                return this.objectIDField;
            }
            set {
                this.objectIDField = value;
            }
        }
        
        /// <remarks/>
        public CreditRegisterDeliveryInfoCreditContractsContractBalance Balance {
            get {
                return this.balanceField;
            }
            set {
                this.balanceField = value;
            }
        }
        
        /// <remarks/>
        public CreditRegisterDeliveryInfoCreditContractsContractAuxInfo AuxInfo {
            get {
                return this.auxInfoField;
            }
            set {
                this.auxInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="date")]
        public System.DateTime startDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="date")]
        public System.DateTime endDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool endDateSpecified {
            get {
                return this.endDateFieldSpecified;
            }
            set {
                this.endDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public Remark_ST remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool remarkSpecified {
            get {
                return this.remarkFieldSpecified;
            }
            set {
                this.remarkFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.uc.se/integration/schema/external/sharkV2")]
    public partial class CreditRegisterDeliveryInfoCreditContractsContractAccountNum {
        
        private string refNumField;
        
        private int creditTypeField;
        
        private string productNameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string refNum {
            get {
                return this.refNumField;
            }
            set {
                this.refNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public int creditType {
            get {
                return this.creditTypeField;
            }
            set {
                this.creditTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string productName {
            get {
                return this.productNameField;
            }
            set {
                this.productNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.uc.se/integration/schema/external/sharkV2")]
    public partial class CreditRegisterDeliveryInfoCreditContractsContractObjectID {
        
        private CreditRegisterDeliveryInfoCreditContractsContractObjectIDIdType idTypeField;
        
        private bool coApplicantField;
        
        private CountryCode_ST countryField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public CreditRegisterDeliveryInfoCreditContractsContractObjectIDIdType idType {
            get {
                return this.idTypeField;
            }
            set {
                this.idTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public bool coApplicant {
            get {
                return this.coApplicantField;
            }
            set {
                this.coApplicantField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public CountryCode_ST country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.uc.se/integration/schema/external/sharkV2")]
    public enum CreditRegisterDeliveryInfoCreditContractsContractObjectIDIdType {
        
        /// <remarks/>
        PersonalIDNum,
        
        /// <remarks/>
        CorporateIDNum,
        
        /// <remarks/>
        CoordinationIDNum,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.uc.se/integration/schema/external/sharkV2")]
    public enum CountryCode_ST {
        
        /// <remarks/>
        SE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.uc.se/integration/schema/external/sharkV2")]
    public partial class CreditRegisterDeliveryInfoCreditContractsContractBalance {
        
        private System.DateTime timeStampField;
        
        private Currency_ST currencyField;
        
        private decimal limitField;
        
        private decimal amountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public System.DateTime timeStamp {
            get {
                return this.timeStampField;
            }
            set {
                this.timeStampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public Currency_ST currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public decimal limit {
            get {
                return this.limitField;
            }
            set {
                this.limitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public decimal amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.uc.se/integration/schema/external/sharkV2")]
    public enum Currency_ST {
        
        /// <remarks/>
        SEK,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.uc.se/integration/schema/external/sharkV2")]
    public partial class CreditRegisterDeliveryInfoCreditContractsContractAuxInfo {
        
        private decimal originalCreditAmountField;
        
        private bool originalCreditAmountFieldSpecified;
        
        private string daysLateField;
        
        private bool dpd90Field;
        
        private bool dpd90FieldSpecified;
        
        private int behaviourCodeField;
        
        private bool behaviourCodeFieldSpecified;
        
        private int wellManagedField;
        
        private bool wellManagedFieldSpecified;
        
        private decimal maturityField;
        
        private bool maturityFieldSpecified;
        
        private int priorCreditTypeField;
        
        private bool priorCreditTypeFieldSpecified;
        
        private string priorRefNumField;
        
        private string priorAccountNumField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public decimal originalCreditAmount {
            get {
                return this.originalCreditAmountField;
            }
            set {
                this.originalCreditAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool originalCreditAmountSpecified {
            get {
                return this.originalCreditAmountFieldSpecified;
            }
            set {
                this.originalCreditAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="integer")]
        public string daysLate {
            get {
                return this.daysLateField;
            }
            set {
                this.daysLateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public bool dpd90 {
            get {
                return this.dpd90Field;
            }
            set {
                this.dpd90Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dpd90Specified {
            get {
                return this.dpd90FieldSpecified;
            }
            set {
                this.dpd90FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public int behaviourCode {
            get {
                return this.behaviourCodeField;
            }
            set {
                this.behaviourCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool behaviourCodeSpecified {
            get {
                return this.behaviourCodeFieldSpecified;
            }
            set {
                this.behaviourCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public int wellManaged {
            get {
                return this.wellManagedField;
            }
            set {
                this.wellManagedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool wellManagedSpecified {
            get {
                return this.wellManagedFieldSpecified;
            }
            set {
                this.wellManagedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public decimal maturity {
            get {
                return this.maturityField;
            }
            set {
                this.maturityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maturitySpecified {
            get {
                return this.maturityFieldSpecified;
            }
            set {
                this.maturityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public int priorCreditType {
            get {
                return this.priorCreditTypeField;
            }
            set {
                this.priorCreditTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool priorCreditTypeSpecified {
            get {
                return this.priorCreditTypeFieldSpecified;
            }
            set {
                this.priorCreditTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string priorRefNum {
            get {
                return this.priorRefNumField;
            }
            set {
                this.priorRefNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string priorAccountNum {
            get {
                return this.priorAccountNumField;
            }
            set {
                this.priorAccountNumField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.uc.se/integration/schema/external/sharkV2")]
    public enum Remark_ST {
        
        /// <remarks/>
        MI,
        
        /// <remarks/>
        ML,
        
        /// <remarks/>
        MK,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.uc.se/integration/schema/external/sharkV2")]
    public partial class CreditRegisterNoDeliveryToday {
        
        private string creditorIDField;
        
        private string sourceSystemIDField;
        
        private string deliveryUniqueIDField;
        
        private System.DateTime deliveryTimeStampField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string creditorID {
            get {
                return this.creditorIDField;
            }
            set {
                this.creditorIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string sourceSystemID {
            get {
                return this.sourceSystemIDField;
            }
            set {
                this.sourceSystemIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string deliveryUniqueID {
            get {
                return this.deliveryUniqueIDField;
            }
            set {
                this.deliveryUniqueIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public System.DateTime deliveryTimeStamp {
            get {
                return this.deliveryTimeStampField;
            }
            set {
                this.deliveryTimeStampField = value;
            }
        }
    }
}
