//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nCustomer.TrapetsKycService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryAttributes", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class QueryAttributes : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AttributeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private nCustomer.TrapetsKycService.ArrayOfString KeywordsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private nCustomer.TrapetsKycService.Country[] CountriesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BirthDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SsnField;
        
        private bool IsSoundExField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AttributeId {
            get {
                return this.AttributeIdField;
            }
            set {
                if ((object.ReferenceEquals(this.AttributeIdField, value) != true)) {
                    this.AttributeIdField = value;
                    this.RaisePropertyChanged("AttributeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public nCustomer.TrapetsKycService.ArrayOfString Keywords {
            get {
                return this.KeywordsField;
            }
            set {
                if ((object.ReferenceEquals(this.KeywordsField, value) != true)) {
                    this.KeywordsField = value;
                    this.RaisePropertyChanged("Keywords");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public nCustomer.TrapetsKycService.Country[] Countries {
            get {
                return this.CountriesField;
            }
            set {
                if ((object.ReferenceEquals(this.CountriesField, value) != true)) {
                    this.CountriesField = value;
                    this.RaisePropertyChanged("Countries");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string BirthDate {
            get {
                return this.BirthDateField;
            }
            set {
                if ((object.ReferenceEquals(this.BirthDateField, value) != true)) {
                    this.BirthDateField = value;
                    this.RaisePropertyChanged("BirthDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Ssn {
            get {
                return this.SsnField;
            }
            set {
                if ((object.ReferenceEquals(this.SsnField, value) != true)) {
                    this.SsnField = value;
                    this.RaisePropertyChanged("Ssn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public bool IsSoundEx {
            get {
                return this.IsSoundExField;
            }
            set {
                if ((this.IsSoundExField.Equals(value) != true)) {
                    this.IsSoundExField = value;
                    this.RaisePropertyChanged("IsSoundEx");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Country", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Country : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AttributeIdField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TwoLetterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ThreeLetterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AttributeId {
            get {
                return this.AttributeIdField;
            }
            set {
                if ((object.ReferenceEquals(this.AttributeIdField, value) != true)) {
                    this.AttributeIdField = value;
                    this.RaisePropertyChanged("AttributeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TwoLetter {
            get {
                return this.TwoLetterField;
            }
            set {
                if ((object.ReferenceEquals(this.TwoLetterField, value) != true)) {
                    this.TwoLetterField = value;
                    this.RaisePropertyChanged("TwoLetter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ThreeLetter {
            get {
                return this.ThreeLetterField;
            }
            set {
                if ((object.ReferenceEquals(this.ThreeLetterField, value) != true)) {
                    this.ThreeLetterField = value;
                    this.RaisePropertyChanged("ThreeLetter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryResult", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class QueryResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AttributeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private nCustomer.TrapetsKycService.Individual[] IndividualsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private nCustomer.TrapetsKycService.Entity[] EntitiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private nCustomer.TrapetsKycService.Country[] CountriesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AttributeId {
            get {
                return this.AttributeIdField;
            }
            set {
                if ((object.ReferenceEquals(this.AttributeIdField, value) != true)) {
                    this.AttributeIdField = value;
                    this.RaisePropertyChanged("AttributeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public nCustomer.TrapetsKycService.Individual[] Individuals {
            get {
                return this.IndividualsField;
            }
            set {
                if ((object.ReferenceEquals(this.IndividualsField, value) != true)) {
                    this.IndividualsField = value;
                    this.RaisePropertyChanged("Individuals");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public nCustomer.TrapetsKycService.Entity[] Entities {
            get {
                return this.EntitiesField;
            }
            set {
                if ((object.ReferenceEquals(this.EntitiesField, value) != true)) {
                    this.EntitiesField = value;
                    this.RaisePropertyChanged("Entities");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public nCustomer.TrapetsKycService.Country[] Countries {
            get {
                return this.CountriesField;
            }
            set {
                if ((object.ReferenceEquals(this.CountriesField, value) != true)) {
                    this.CountriesField = value;
                    this.RaisePropertyChanged("Countries");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Individual", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Individual : nCustomer.TrapetsKycService.ListItem {
        
        private System.Nullable<bool> IsMaleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FunctionDescriptionField;
        
        private System.Nullable<System.DateTime> BirthDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OriginalBirthDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SsnField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<bool> IsMale {
            get {
                return this.IsMaleField;
            }
            set {
                if ((this.IsMaleField.Equals(value) != true)) {
                    this.IsMaleField = value;
                    this.RaisePropertyChanged("IsMale");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string FunctionDescription {
            get {
                return this.FunctionDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.FunctionDescriptionField, value) != true)) {
                    this.FunctionDescriptionField = value;
                    this.RaisePropertyChanged("FunctionDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<System.DateTime> BirthDate {
            get {
                return this.BirthDateField;
            }
            set {
                if ((this.BirthDateField.Equals(value) != true)) {
                    this.BirthDateField = value;
                    this.RaisePropertyChanged("BirthDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string OriginalBirthDate {
            get {
                return this.OriginalBirthDateField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginalBirthDateField, value) != true)) {
                    this.OriginalBirthDateField = value;
                    this.RaisePropertyChanged("OriginalBirthDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Ssn {
            get {
                return this.SsnField;
            }
            set {
                if ((object.ReferenceEquals(this.SsnField, value) != true)) {
                    this.SsnField = value;
                    this.RaisePropertyChanged("Ssn");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Entity", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Entity : nCustomer.TrapetsKycService.ListItem {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListItem", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(nCustomer.TrapetsKycService.Entity))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(nCustomer.TrapetsKycService.Individual))]
    public partial class ListItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AttributeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExternalIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        private System.Nullable<System.DateTime> PostDateField;
        
        private System.Nullable<System.DateTime> LastUpdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ListTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XmlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private nCustomer.TrapetsKycService.ArrayOfString AliasesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private nCustomer.TrapetsKycService.ArrayOfString AddressesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private nCustomer.TrapetsKycService.ArrayOfString ExternalUrlsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string AttributeId {
            get {
                return this.AttributeIdField;
            }
            set {
                if ((object.ReferenceEquals(this.AttributeIdField, value) != true)) {
                    this.AttributeIdField = value;
                    this.RaisePropertyChanged("AttributeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ExternalId {
            get {
                return this.ExternalIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ExternalIdField, value) != true)) {
                    this.ExternalIdField = value;
                    this.RaisePropertyChanged("ExternalId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<System.DateTime> PostDate {
            get {
                return this.PostDateField;
            }
            set {
                if ((this.PostDateField.Equals(value) != true)) {
                    this.PostDateField = value;
                    this.RaisePropertyChanged("PostDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<System.DateTime> LastUpdate {
            get {
                return this.LastUpdateField;
            }
            set {
                if ((this.LastUpdateField.Equals(value) != true)) {
                    this.LastUpdateField = value;
                    this.RaisePropertyChanged("LastUpdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string SourceName {
            get {
                return this.SourceNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceNameField, value) != true)) {
                    this.SourceNameField = value;
                    this.RaisePropertyChanged("SourceName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string ListType {
            get {
                return this.ListTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ListTypeField, value) != true)) {
                    this.ListTypeField = value;
                    this.RaisePropertyChanged("ListType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string Xml {
            get {
                return this.XmlField;
            }
            set {
                if ((object.ReferenceEquals(this.XmlField, value) != true)) {
                    this.XmlField = value;
                    this.RaisePropertyChanged("Xml");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public nCustomer.TrapetsKycService.ArrayOfString Aliases {
            get {
                return this.AliasesField;
            }
            set {
                if ((object.ReferenceEquals(this.AliasesField, value) != true)) {
                    this.AliasesField = value;
                    this.RaisePropertyChanged("Aliases");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public nCustomer.TrapetsKycService.ArrayOfString Addresses {
            get {
                return this.AddressesField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressesField, value) != true)) {
                    this.AddressesField = value;
                    this.RaisePropertyChanged("Addresses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public nCustomer.TrapetsKycService.ArrayOfString ExternalUrls {
            get {
                return this.ExternalUrlsField;
            }
            set {
                if ((object.ReferenceEquals(this.ExternalUrlsField, value) != true)) {
                    this.ExternalUrlsField = value;
                    this.RaisePropertyChanged("ExternalUrls");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TrapetsKycService.ListLookupSoap")]
    public interface ListLookupSoap {
        
        // CODEGEN: Generating message contract since element name userName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DoQuery", ReplyAction="*")]
        nCustomer.TrapetsKycService.DoQueryResponse DoQuery(nCustomer.TrapetsKycService.DoQueryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DoQuery", ReplyAction="*")]
        System.Threading.Tasks.Task<nCustomer.TrapetsKycService.DoQueryResponse> DoQueryAsync(nCustomer.TrapetsKycService.DoQueryRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetIndividualByExternalId", ReplyAction="*")]
        nCustomer.TrapetsKycService.GetIndividualByExternalIdResponse GetIndividualByExternalId(nCustomer.TrapetsKycService.GetIndividualByExternalIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetIndividualByExternalId", ReplyAction="*")]
        System.Threading.Tasks.Task<nCustomer.TrapetsKycService.GetIndividualByExternalIdResponse> GetIndividualByExternalIdAsync(nCustomer.TrapetsKycService.GetIndividualByExternalIdRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEntityByExternalId", ReplyAction="*")]
        nCustomer.TrapetsKycService.GetEntityByExternalIdResponse GetEntityByExternalId(nCustomer.TrapetsKycService.GetEntityByExternalIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEntityByExternalId", ReplyAction="*")]
        System.Threading.Tasks.Task<nCustomer.TrapetsKycService.GetEntityByExternalIdResponse> GetEntityByExternalIdAsync(nCustomer.TrapetsKycService.GetEntityByExternalIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DoQueryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DoQuery", Namespace="http://tempuri.org/", Order=0)]
        public nCustomer.TrapetsKycService.DoQueryRequestBody Body;
        
        public DoQueryRequest() {
        }
        
        public DoQueryRequest(nCustomer.TrapetsKycService.DoQueryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DoQueryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string serviceName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public nCustomer.TrapetsKycService.QueryAttributes[] attr;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public bool matchAllNames;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool useSoundEx;
        
        public DoQueryRequestBody() {
        }
        
        public DoQueryRequestBody(string userName, string password, string serviceName, nCustomer.TrapetsKycService.QueryAttributes[] attr, bool matchAllNames, bool useSoundEx) {
            this.userName = userName;
            this.password = password;
            this.serviceName = serviceName;
            this.attr = attr;
            this.matchAllNames = matchAllNames;
            this.useSoundEx = useSoundEx;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DoQueryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DoQueryResponse", Namespace="http://tempuri.org/", Order=0)]
        public nCustomer.TrapetsKycService.DoQueryResponseBody Body;
        
        public DoQueryResponse() {
        }
        
        public DoQueryResponse(nCustomer.TrapetsKycService.DoQueryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DoQueryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public nCustomer.TrapetsKycService.QueryResult[] DoQueryResult;
        
        public DoQueryResponseBody() {
        }
        
        public DoQueryResponseBody(nCustomer.TrapetsKycService.QueryResult[] DoQueryResult) {
            this.DoQueryResult = DoQueryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetIndividualByExternalIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetIndividualByExternalId", Namespace="http://tempuri.org/", Order=0)]
        public nCustomer.TrapetsKycService.GetIndividualByExternalIdRequestBody Body;
        
        public GetIndividualByExternalIdRequest() {
        }
        
        public GetIndividualByExternalIdRequest(nCustomer.TrapetsKycService.GetIndividualByExternalIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetIndividualByExternalIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string serviceName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string externalId;
        
        public GetIndividualByExternalIdRequestBody() {
        }
        
        public GetIndividualByExternalIdRequestBody(string userName, string password, string serviceName, string externalId) {
            this.userName = userName;
            this.password = password;
            this.serviceName = serviceName;
            this.externalId = externalId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetIndividualByExternalIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetIndividualByExternalIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public nCustomer.TrapetsKycService.GetIndividualByExternalIdResponseBody Body;
        
        public GetIndividualByExternalIdResponse() {
        }
        
        public GetIndividualByExternalIdResponse(nCustomer.TrapetsKycService.GetIndividualByExternalIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetIndividualByExternalIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public nCustomer.TrapetsKycService.Individual GetIndividualByExternalIdResult;
        
        public GetIndividualByExternalIdResponseBody() {
        }
        
        public GetIndividualByExternalIdResponseBody(nCustomer.TrapetsKycService.Individual GetIndividualByExternalIdResult) {
            this.GetIndividualByExternalIdResult = GetIndividualByExternalIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEntityByExternalIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEntityByExternalId", Namespace="http://tempuri.org/", Order=0)]
        public nCustomer.TrapetsKycService.GetEntityByExternalIdRequestBody Body;
        
        public GetEntityByExternalIdRequest() {
        }
        
        public GetEntityByExternalIdRequest(nCustomer.TrapetsKycService.GetEntityByExternalIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEntityByExternalIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string serviceName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string externalId;
        
        public GetEntityByExternalIdRequestBody() {
        }
        
        public GetEntityByExternalIdRequestBody(string userName, string password, string serviceName, string externalId) {
            this.userName = userName;
            this.password = password;
            this.serviceName = serviceName;
            this.externalId = externalId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEntityByExternalIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEntityByExternalIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public nCustomer.TrapetsKycService.GetEntityByExternalIdResponseBody Body;
        
        public GetEntityByExternalIdResponse() {
        }
        
        public GetEntityByExternalIdResponse(nCustomer.TrapetsKycService.GetEntityByExternalIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEntityByExternalIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public nCustomer.TrapetsKycService.Entity GetEntityByExternalIdResult;
        
        public GetEntityByExternalIdResponseBody() {
        }
        
        public GetEntityByExternalIdResponseBody(nCustomer.TrapetsKycService.Entity GetEntityByExternalIdResult) {
            this.GetEntityByExternalIdResult = GetEntityByExternalIdResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ListLookupSoapChannel : nCustomer.TrapetsKycService.ListLookupSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ListLookupSoapClient : System.ServiceModel.ClientBase<nCustomer.TrapetsKycService.ListLookupSoap>, nCustomer.TrapetsKycService.ListLookupSoap {
        
        public ListLookupSoapClient() {
        }
        
        public ListLookupSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ListLookupSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ListLookupSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ListLookupSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        nCustomer.TrapetsKycService.DoQueryResponse nCustomer.TrapetsKycService.ListLookupSoap.DoQuery(nCustomer.TrapetsKycService.DoQueryRequest request) {
            return base.Channel.DoQuery(request);
        }
        
        public nCustomer.TrapetsKycService.QueryResult[] DoQuery(string userName, string password, string serviceName, nCustomer.TrapetsKycService.QueryAttributes[] attr, bool matchAllNames, bool useSoundEx) {
            nCustomer.TrapetsKycService.DoQueryRequest inValue = new nCustomer.TrapetsKycService.DoQueryRequest();
            inValue.Body = new nCustomer.TrapetsKycService.DoQueryRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.serviceName = serviceName;
            inValue.Body.attr = attr;
            inValue.Body.matchAllNames = matchAllNames;
            inValue.Body.useSoundEx = useSoundEx;
            nCustomer.TrapetsKycService.DoQueryResponse retVal = ((nCustomer.TrapetsKycService.ListLookupSoap)(this)).DoQuery(inValue);
            return retVal.Body.DoQueryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<nCustomer.TrapetsKycService.DoQueryResponse> nCustomer.TrapetsKycService.ListLookupSoap.DoQueryAsync(nCustomer.TrapetsKycService.DoQueryRequest request) {
            return base.Channel.DoQueryAsync(request);
        }
        
        public System.Threading.Tasks.Task<nCustomer.TrapetsKycService.DoQueryResponse> DoQueryAsync(string userName, string password, string serviceName, nCustomer.TrapetsKycService.QueryAttributes[] attr, bool matchAllNames, bool useSoundEx) {
            nCustomer.TrapetsKycService.DoQueryRequest inValue = new nCustomer.TrapetsKycService.DoQueryRequest();
            inValue.Body = new nCustomer.TrapetsKycService.DoQueryRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.serviceName = serviceName;
            inValue.Body.attr = attr;
            inValue.Body.matchAllNames = matchAllNames;
            inValue.Body.useSoundEx = useSoundEx;
            return ((nCustomer.TrapetsKycService.ListLookupSoap)(this)).DoQueryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        nCustomer.TrapetsKycService.GetIndividualByExternalIdResponse nCustomer.TrapetsKycService.ListLookupSoap.GetIndividualByExternalId(nCustomer.TrapetsKycService.GetIndividualByExternalIdRequest request) {
            return base.Channel.GetIndividualByExternalId(request);
        }
        
        public nCustomer.TrapetsKycService.Individual GetIndividualByExternalId(string userName, string password, string serviceName, string externalId) {
            nCustomer.TrapetsKycService.GetIndividualByExternalIdRequest inValue = new nCustomer.TrapetsKycService.GetIndividualByExternalIdRequest();
            inValue.Body = new nCustomer.TrapetsKycService.GetIndividualByExternalIdRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.serviceName = serviceName;
            inValue.Body.externalId = externalId;
            nCustomer.TrapetsKycService.GetIndividualByExternalIdResponse retVal = ((nCustomer.TrapetsKycService.ListLookupSoap)(this)).GetIndividualByExternalId(inValue);
            return retVal.Body.GetIndividualByExternalIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<nCustomer.TrapetsKycService.GetIndividualByExternalIdResponse> nCustomer.TrapetsKycService.ListLookupSoap.GetIndividualByExternalIdAsync(nCustomer.TrapetsKycService.GetIndividualByExternalIdRequest request) {
            return base.Channel.GetIndividualByExternalIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<nCustomer.TrapetsKycService.GetIndividualByExternalIdResponse> GetIndividualByExternalIdAsync(string userName, string password, string serviceName, string externalId) {
            nCustomer.TrapetsKycService.GetIndividualByExternalIdRequest inValue = new nCustomer.TrapetsKycService.GetIndividualByExternalIdRequest();
            inValue.Body = new nCustomer.TrapetsKycService.GetIndividualByExternalIdRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.serviceName = serviceName;
            inValue.Body.externalId = externalId;
            return ((nCustomer.TrapetsKycService.ListLookupSoap)(this)).GetIndividualByExternalIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        nCustomer.TrapetsKycService.GetEntityByExternalIdResponse nCustomer.TrapetsKycService.ListLookupSoap.GetEntityByExternalId(nCustomer.TrapetsKycService.GetEntityByExternalIdRequest request) {
            return base.Channel.GetEntityByExternalId(request);
        }
        
        public nCustomer.TrapetsKycService.Entity GetEntityByExternalId(string userName, string password, string serviceName, string externalId) {
            nCustomer.TrapetsKycService.GetEntityByExternalIdRequest inValue = new nCustomer.TrapetsKycService.GetEntityByExternalIdRequest();
            inValue.Body = new nCustomer.TrapetsKycService.GetEntityByExternalIdRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.serviceName = serviceName;
            inValue.Body.externalId = externalId;
            nCustomer.TrapetsKycService.GetEntityByExternalIdResponse retVal = ((nCustomer.TrapetsKycService.ListLookupSoap)(this)).GetEntityByExternalId(inValue);
            return retVal.Body.GetEntityByExternalIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<nCustomer.TrapetsKycService.GetEntityByExternalIdResponse> nCustomer.TrapetsKycService.ListLookupSoap.GetEntityByExternalIdAsync(nCustomer.TrapetsKycService.GetEntityByExternalIdRequest request) {
            return base.Channel.GetEntityByExternalIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<nCustomer.TrapetsKycService.GetEntityByExternalIdResponse> GetEntityByExternalIdAsync(string userName, string password, string serviceName, string externalId) {
            nCustomer.TrapetsKycService.GetEntityByExternalIdRequest inValue = new nCustomer.TrapetsKycService.GetEntityByExternalIdRequest();
            inValue.Body = new nCustomer.TrapetsKycService.GetEntityByExternalIdRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.serviceName = serviceName;
            inValue.Body.externalId = externalId;
            return ((nCustomer.TrapetsKycService.ListLookupSoap)(this)).GetEntityByExternalIdAsync(inValue);
        }
    }
}
