// <auto-generated />
namespace nPreCredit.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PreventDupesInCreditApplicationItem : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PreventDupesInCreditApplicationItem));
        
        string IMigrationMetadata.Id
        {
            get { return "201609090721137_PreventDupesInCreditApplicationItem"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
